import type { APIRoute } from 'astro';
import { getCollection, type CollectionEntry } from 'astro:content';
// Not in the package's exports, so imported from its source (pinned in package.json). It is the plugin's
// MDX -> markdown pipeline, including the handling of Starlight's components (asides, tabs, cards, code).
import { entryToSimpleMarkdown } from '../../node_modules/starlight-llms-txt/entryToSimpleMarkdown';
import { sidebar } from '../sidebar.mjs';

/**
 * The whole documentation as one text file for LLMs (replaces the route starlight-llms-txt would generate):
 * pages in sidebar order, each starting with a heading that carries its navigation path and a `Source:` line with
 * the page url, so that a tool searching this text can return citable, self-describing sections.
 */

const SITE = 'https://docs.diploi.com';

type SidebarItem =
  | string
  | { label?: string; link?: string; slug?: string; items?: SidebarItem[]; autogenerate?: { directory: string } };

/** The pages of an autogenerated sidebar group, in the order Starlight lists them (`sidebar.order`, then id) */
const autogeneratedPages = (directory: string, docs: CollectionEntry<'docs'>[]) => {
  const prefix = `${directory.replace(/^\/|\/$/g, '')}/`;
  return docs
    .filter((doc) => doc.id.startsWith(prefix))
    .sort((a, b) => {
      const [aOrder, bOrder] = [a.data.sidebar.order ?? Infinity, b.data.sidebar.order ?? Infinity];
      if (aOrder !== bOrder) return aOrder < bOrder ? -1 : 1;
      return a.id.localeCompare(b.id, 'en');
    })
    .map((doc) => doc.id);
};

/** Pages in navigation order, with the labels of the groups they are in */
const flattenSidebar = (items: SidebarItem[], docs: CollectionEntry<'docs'>[], groups: string[] = []): { id: string; groups: string[] }[] =>
  items.flatMap((item) => {
    if (typeof item === 'string') return [{ id: item, groups }];
    const itemGroups = item.label ? [...groups, item.label] : groups;
    if (item.autogenerate) return autogeneratedPages(item.autogenerate.directory, docs).map((id) => ({ id, groups: itemGroups }));
    if (item.items) return flattenSidebar(item.items, docs, itemGroups);
    if (item.slug) return [{ id: item.slug, groups }];
    if (item.link) {
      // Internal page links only ("/", "/get-started"), not files like /llms.txt or external urls
      if (/^https?:|\./.test(item.link)) return [];
      return [{ id: item.link.replace(/^\/|\/$/g, '') || 'index', groups }];
    }
    return [];
  });

const pageUrl = (id: string) => (id === 'index' ? `${SITE}/` : `${SITE}/${id}`);

export const GET: APIRoute = async (context) => {
  const docs = await getCollection('docs', (doc) => !doc.data.draft);
  const byId = new Map<string, CollectionEntry<'docs'>>(docs.map((doc) => [doc.id, doc]));

  const ordered = flattenSidebar(sidebar as SidebarItem[], docs).filter(({ id }) => byId.has(id));
  // Pages that are not in the navigation come last
  const listed = new Set(ordered.map(({ id }) => id));
  for (const doc of [...docs].sort((a, b) => a.id.localeCompare(b.id))) {
    if (!listed.has(doc.id)) ordered.push({ id: doc.id, groups: [] });
  }

  const pages: string[] = [];
  for (const { id, groups } of ordered) {
    const doc = byId.get(id)!;
    const description = doc.data.hero?.tagline || doc.data.description;
    const body = await entryToSimpleMarkdown(doc, context);
    // The navigation path with the page title, without repeating a group that is named like the page
    const path = [...groups.filter((group, i) => i < groups.length - 1 || group !== doc.data.title), doc.data.title];
    pages.push(
      [`# ${path.join(' › ')}`, `Source: ${pageUrl(id)}`, description ? `> ${description}` : null, '', body]
        .filter((line) => line !== null)
        .join('\n')
    );
  }

  const intro = [
    '# Diploi documentation',
    '',
    `The documentation of Diploi (${SITE}) as one text. Every "# " heading is a page (its navigation path, then the`,
    'page url on a "Source:" line and its summary), the headings below it are the sections of that page.',
  ].join('\n');

  return new Response(`${intro}\n\n${pages.join('\n\n')}\n`, { headers: { 'Content-Type': 'text/plain; charset=utf-8' } });
};
