name: Build Components

on:
  push:
    branches:
      - '*'

jobs:
  define-components:
    name: Define Components
    runs-on: ubuntu-latest
    outputs:
      components: ${{ steps.diploi-meta.outputs.components }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - id: diploi-meta
        name: Diploi meta
        uses: diploi/action-components@v1.6-alpha
  run-builds:
    name: Build ${{ matrix.name }} ${{ matrix.stage }}
    runs-on: ubuntu-latest
    needs: define-components
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.define-components.outputs.components) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Diploi build
        uses: diploi/action-build@v1.6-alpha
        with: ${{ matrix }}
        env:
          project: ${{ secrets.DIPLOI_REGISTRY_PROJECT }}
          registry: ${{ secrets.DIPLOI_REGISTRY_HOSTNAME }}
          username: ${{ secrets.DIPLOI_REGISTRY_USER }}
          password: ${{ secrets.DIPLOI_REGISTRY_SECRET }}